### ISSUE TITLE
Is this the built project?

### ISSUE THREAD

**Issue by aarongustafson** [nternetinspired/10K-Circus#3]
We are getting ready to deploy it but I don’t see an index file.

**Comment by nternetinspired** [comment]
Sorry, the site is built with Jekyll, so the compiled site is at `_site`. https://github.com/nternetinspired/10K-Circus/tree/master/_site

Sorry for any inconvenience.

**Comment by nternetinspired** [comment]
Pushing the source means I get to show my workings, as compiled version is compressed every way possible it's not so human-readable; which is why I decided to included the source also.

**Comment by nternetinspired** [comment]
Hi @aarongustafson,

Sorry, but I've just noticed that the Azure site seems to _only_ have the index page. 

Both /about/index.html and /404/index.html pages are missing from the deployed site. Can you please re-deploy with all three index files? That will also fix the issue addressed in my last update: https://github.com/nternetinspired/10K-Circus/commit/ef0951e490e749533a746357c72a5acca640c62f 

Thanks.

**Comment by nternetinspired** [comment]
Sorry! Just noticed this was my fault and you did indeed deploy all pages @aarongustafson. My last build was configured for living on GH Pages still!

Nevertheless, it would be great if you _could_ re-deploy these three pages for me. The internal links are fixed in my last commit: https://github.com/nternetinspired/10K-Circus/commit/caec7e2c8440c85c0f6e4877e42dcb8291bca2e5

Thank you! 🙇

**Comment by aarongustafson** [comment]
I just triggered the deploy and it looks like it was successful. Take a look.

**Comment by nternetinspired** [comment]
Perfect! 

:shipit: 

Thank you @aarongustafson I owe you 🍺
